[debian_servers]
samba-ad-sub ansible_host=samba-ad-sub.japan-is.fun
vault        ansible_host=vault.japan-is.fun
lxc-ssh   ansible_host=lxc-ssh.japan-is.fun 

[debian_servers:vars]
ansible_user=ldapci-user