name: ansible cloudflared

on:
  workflow_call:
    inputs:
      ansible_dir:
        required: true
        type: string
        description: "ansibleを実行するディレクトリ "
      ansible_command:
        required: true
        type: string
        description: "実行するansibleコマンド"

jobs:
  ansible-update-job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Import Secrets from Vault
        id: vault
        uses: hashicorp/vault-action@892a26828f195e65540a40b4768ae4571f51ebfc
        with:
          url: ${{ secrets.VAULT_ADDR }}
          role: github-actions-role
          method: jwt
          path: jwt-github
          exportToken: false
          outputToken: true
          extraHeaders: |
            CF-Access-Client-Id: ${{ secrets.TUNNEL_SERVICE_TOKEN_ID }}
            CF-Access-Client-Secret: ${{ secrets.TUNNEL_SERVICE_TOKEN_SECRET }}
          secrets: |
            secret/data/ansible/known_hosts known_hosts | SSH_KNOWN_HOSTS ;
            secret/data/ansible/hosts_ini debian | HOSTS_DEBIAN ;
            secret/data/ansible/hosts_ini proxmox | HOSTS_PROXMOX ;
            secret/data/ansible/hosts_ini k3s | HOSTS_K3S ;

      - name: Copy Ansible Config
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          cp ansibleConfig/ansible.cfg ~/.ansible.cfg
          
      - name: install cloudflared
        run: |
         EXPECTED_SHA256="5861a10a438fe8ddcfebb3b830f83966cbf193edafce0fe2eeb198fbae1f7a22"
         
         curl -L https://github.com/cloudflare/cloudflared/releases/download/2026.6.1/cloudflared-linux-amd64 \
         -o /usr/local/bin/cloudflared

         echo "${EXPECTED_SHA256}  /usr/local/bin/cloudflared" | sha256sum -c -

         chmod +x /usr/local/bin/cloudflared

      - name: run ansible
        env:
          ANSIBLE_SSH_COMMON_ARGS: >-
                      -o ProxyCommand="/usr/local/bin/cloudflared access ssh --hostname %h"
          
          VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
          VAULT_TOKEN: ${{ steps.vault.outputs.vault_token }}
          TUNNEL_SERVICE_TOKEN_ID: ${{ secrets.TUNNEL_SERVICE_TOKEN_ID }}
          TUNNEL_SERVICE_TOKEN_SECRET: ${{ secrets.TUNNEL_SERVICE_TOKEN_SECRET }}
          
        run: |
          cd ${{ inputs.ansible_dir }}

          echo "$HOSTS_DEBIAN" > hosts.ini
          echo "" >> hosts.ini
          echo "$HOSTS_PROXMOX" >> hosts.ini
          echo "" >> hosts.ini
          echo "$HOSTS_K3S" >> hosts.ini
          
          ansible-playbook -i hosts.ini ${{ inputs.ansible_command }}
