name: Update PVE
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-cloudflared-ansible.yml
    with:
      ansible_dir: "proxmox"
      ansible_command: "update_pve.yml"
    secrets: inherit